### ISSUE TITLE
Plugin.js.map is missing - throws as 404

### ISSUE THREAD

**Issue by paavo** [Unikka/login-as#17]
The `Resources/Public/LoginAsUserMenu/Plugin.js.map` referenced in [Plugin.js](https://github.com/Unikka/login-as/blob/master/Resources/Public/LoginAsUserMenu/Plugin.js#L1378) is missing. 
This throws as 404 in DevTools. 

Not a real issue, but nice if this would be fixed.

**Comment by markusguenther** [comment]
Thanks for reporting that :)

**Comment by paavo** [comment]
May we fix this someday @markusguenther? 🙏 
I always trigger when i see this warning in backend 🤣

**Comment by markusguenther** [comment]
Fun fact ... that does not happen in Firefox. And that is my main browser.

**Chrome:**
<img width="711" alt="Screenshot 2022-05-20 at 13 38 52" src="https://user-images.githubusercontent.com/1014126/169520929-fc2c824d-6908-443d-92af-7f9c8f9024b5.png">

**Firefox:**
<img width="846" alt="Screenshot 2022-05-20 at 13 39 15" src="https://user-images.githubusercontent.com/1014126/169520933-1b3c8db1-86a1-4c60-8a07-2ed9236b16e7.png">

**Comment by markusguenther** [comment]
This will be fixed soon.
https://github.com/Unikka/login-as/commit/d4ab9d097633104f0e92d87664b5441e86b8ca11

**Comment by markusguenther** [comment]
Fixed in version 2.0.3

**Comment by markusguenther** [comment]
The change worked locally, but with the release version, we have the same. As I also get Map issues from Neos.Neos it is maybe a mistake in the webpack build. Will check it there.
