### ISSUE TITLE
Exclude Module\Management\Workspaces in the Views requestFilter

### ISSUE THREAD

**Issue by jobee** [Unikka/login-as#18]
### Description

Is there any chance to add `&& !isController("Module\Management\Workspaces")` to the list of excluded modules within `requestFilter` ?

Our projects have https://github.com/flownative/neos-workspace-preview installed which overrides the Workspaces Index template. This is not working when LoginAs is installed too :-/

### Steps to Reproduce

1. `composer require flownative/workspace-preview`
2. Open http://localhost:8081/neos/management/workspaces

#### Expected behavior

Rendering Workspaces Index template from `Flownative.WorkspacePreview`

#### Actual behavior

Default Workspace template from `Neos.Neos` gets rendered.

### Affected Versions

Neos: 7.3.1 (the only one tested so far)

LoginAs: v2.0.2

**Comment by markusguenther** [comment]
Thanks for reporting that. Need to check that, but it would be a quick fix.
Finally, it would be nicer to have another way to add assets to the backend.

Because I just do that to be able to extend the user menu :/

**Comment by markusguenther** [comment]
Fixed in version 2.0.3
